
terraform import module.ecs_frontend.aws_ecs_cluster.main eduia-cluster
terraform import module.ecr.aws_ecr_repository.frontend_repo eduia-frontend
terraform import module.ecs_frontend.aws_cloudwatch_log_group.frontend_logs /ecs/eduia-frontend
terraform import module.ecs_frontend.aws_ecs_service.frontend eduia-cluster/eduia-frontend
terraform import module.ecs_frontend.aws_ecs_task_definition.frontend eduia-frontend
terraform import module.ecs_frontend.aws_iam_policy.ecs_exec_command_policy ecs-exec-command-policy
terraform import module.ecs_frontend.aws_iam_role.ecs_task_execution_role eduia-ecs-task-execution-role
terraform import module.ecs_frontend.aws_iam_role.ecs_task_role eduia-ecs-task-role
terraform import module.ecs_frontend.aws_iam_role_policy_attachment.ecs_task_execution_role_policy arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
terraform import module.ecs_frontend.aws_iam_role_policy_attachment.ecs_task_role_policy arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
terraform import module.monitoring.aws_cloudwatch_log_group.monitoring_log_group /ecs/eduia/monitoring
terraform import module.monitoring.aws_cloudwatch_metric_alarm.high_cpu_usage eduia-high-cpu-usage
terraform import module.network.aws_internet_gateway.igw igw-xxxxxxxx
terraform import module.network.aws_route_table.public rtb-xxxxxxxx
terraform import module.network.aws_route_table_association.public_subnet_association[0] rtbassoc-xxxxxxxx
terraform import module.network.aws_route_table_association.public_subnet_association[1] rtbassoc-yyyyyyyy
terraform import module.network.aws_security_group.ecs_sg_frontend sg-xxxxxxxx
terraform import module.network.aws_subnet.public_subnet[0] subnet-xxxxxxxx
terraform import module.network.aws_subnet.public_subnet[1] subnet-yyyyyyyy
terraform import module.network.aws_vpc.main vpc-xxxxxxxx
