name: CI - Build & Test
# Disparador ÚNICO: Se ejecuta solo cuando se abre o actualiza un PR hacia tus ramas principales.
on:
  pull_request:
    branches:
      - main
      - development
      - staging

  workflow_dispatch: # Permite ejecución manual
  
permissions:
  contents: write
env:
  NODE_VERSION: '24.3.0'
  AWS_REGION: us-east-2

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: Install Node.js dependencies
        run: make install-ci

      - name: Lint
        run: make Lint

      - name: Run Unit Tests
        run: make test
